### ISSUE TITLE
Sintesis 

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-CxrlosMX#1]
[Sintesis - Unidad 02.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-CxrlosMX/files/9691781/Sintesis.-.Unidad.02.pdf)

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
